/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int PUBLIC = 2;
  /** RegularExpression Id. */
  int STATIC = 3;
  /** RegularExpression Id. */
  int VOID = 4;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int STRINGTYPE = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int RETURN = 8;
  /** RegularExpression Id. */
  int INTTYPE = 9;
  /** RegularExpression Id. */
  int BOOLEANTYPE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int LENGTH = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int THIS = 19;
  /** RegularExpression Id. */
  int LBRACK = 20;
  /** RegularExpression Id. */
  int RBRACK = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int LSQUARE = 24;
  /** RegularExpression Id. */
  int RSQUARE = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int EQUAL = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int ANDAND = 31;
  /** RegularExpression Id. */
  int PLUS = 32;
  /** RegularExpression Id. */
  int LT = 33;
  /** RegularExpression Id. */
  int MINUS = 34;
  /** RegularExpression Id. */
  int TIMES = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"extends\"",
    "\"return\"",
    "\"int\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"new\"",
    "\"this\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "\"!\"",
    "\"&&\"",
    "\"+\"",
    "\"<\"",
    "\"-\"",
    "\"*\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
